# Copyright 2024 RustFS Team
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Update Homebrew Formulas

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch: {}
  repository_dispatch:
    types: [release]

permissions:
  contents: read

concurrency:
  group: update-homebrew-formulas
  cancel-in-progress: false

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - formula: rustfs
            path: rustfs.rb
          - formula: rc
            path: rc.rb
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4'

      - name: Update formula
        id: update
        env:
          FORMULA: ${{ matrix.formula }}
        run: ruby scripts/update_formula.rb "$FORMULA"

      - name: Validate formulas and updater
        run: |
          ruby -c rc.rb
          ruby -c rustfs.rb
          ruby -c scripts/formula_updater.rb
          ruby -c scripts/update_formula.rb

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          add-paths: ${{ matrix.path }}
          commit-message: "chore: bump ${{ matrix.formula }} formula to ${{ steps.update.outputs.version }}"
          committer: "houseme <housemecn@gmail.com>"
          author: "houseme <housemecn@gmail.com>"
          title: "chore: bump ${{ matrix.formula }} formula to ${{ steps.update.outputs.version }}"
          body: |
            Automated update to the latest ${{ matrix.formula }} release ${{ steps.update.outputs.version }}.
          branch: "update/${{ matrix.formula }}-${{ steps.update.outputs.version }}"
          delete-branch: true
