# Copyright 2024 RustFS Team
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Update Homebrew Formula For RustFS

on:
  schedule:
    - cron: '0 */12 * * *' # twice a day
  workflow_dispatch: { }
  repository_dispatch:
    types: [ release ]

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4'

      - name: Run updater
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_UPSTREAM_REPO: rustfs/rustfs
        run: |
          ruby scripts/update_formula.rb

      - name: Read latest version
        id: v
        run: echo "version=$(cat .latest_version)" >> $GITHUB_OUTPUT

      - name: Cleanup temporary files
        run: rm -f .latest_version

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: bump rustfs formula to ${{ steps.v.outputs.version }}"
          title: "chore: bump rustfs to ${{ steps.v.outputs.version }}"
          body: |
            Automated update to latest release ${{ steps.v.outputs.version }}.
          branch: "update/rustfs-${{ steps.v.outputs.version }}"
          delete-branch: true
